config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get :favs
      get :testimony
      get :login
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :services, :albums, :verses
    resource :privacy
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    resource :photo
    resources :relationships
    resources :people do
      member do
        post :update_position
      end
    end
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resources :tasks do
      member do
        patch :complete
        post :update_position
      end
    end
    resource :stream
    resource :photo
    resources :prayer_requests, :albums
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resource :emails

  put 'setup_email' => 'emails#create_route'

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :shares,
            :comments, :prayer_requests, :generated_files

  resources :verses do
    get 'search', on: :collection
  end

  resource :setup, :session, :search, :printable_directory

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  resources :directory_maps do
    collection do
      get :family_locations
    end
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'
  get '/admin/reports' => 'administration/reports#index'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths, :labels
    end
  end

  resource :checkin, controller: 'checkin/checkins'
  namespace :checkin do
    resource :print
    resource :printer
    resources :families, :people, :groups
  end
  resources :custom_reports

  post '/pusher/auth_printer' => 'pusher#auth_printer'
end

app/models/concerns/person/memberships.rb
require 'active_support/concern'

module Concerns
  module Person
    module Memberships
      extend ActiveSupport::Concern

      included do
        has_many :memberships, dependent: :destroy
        has_many :membership_requests, dependent: :destroy
        has_many :groups, through: :memberships
        after_destroy :destroy_memberships
      end

      def member_of?(group)
        memberships.where(group_id: group.id).any?
      end

      def destroy_memberships
        memberships.destroy_all
        membership_requests.destroy_all
      end
    end
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base

  include Authority::Abilities
  self.authorizer_name = 'MembershipAuthorizer'

  belongs_to :group
  belongs_to :person
  belongs_to :site

  validates_uniqueness_of :group_id, scope: [:site_id, :person_id]

  scope_by_site_id

  scope :order_by_birthday, -> { order('ifnull(month(people.birthday), 99)') }
  scope :order_by_name,     -> { order('people.first_name, people.last_name') }

  def family; person.family; end

  serialize :roles, Array
  validate :validate_roles

  def validate_roles
    if roles.any? { |r| r !~ /\A[a-z0-9 \-_\(\)]+\z/i }
      errors.add(:roles, :invalid)
    end
  end

  before_create :generate_security_code

  def generate_security_code
    begin
      code = rand(999999)
      write_attribute :code, code
    end until code > 0
  end

  def self.sharing_columns
    columns.map { |c| c.name }.select { |c| c =~ /^share_/ }
  end

  def only_admin?
    person and group and
    group.admin?(person, :exclude_global_admins) and
    group.admins.length == 1
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  skip_before_action :authenticate_user, only: %w(show update)
  before_action :authenticate_user_with_code_or_session, only: %w(show update)

  load_parent :group

  before_action :authorize_group_for_read,   only: :index
  before_action :authorize_group_for_update, only: :batch

  def show
    # allow email links to work (since they will be GET requests)
    if params[:email]
      update
    else
      fail ActionController::UnknownAction, t('No_action_to_show')
    end
  end

  def index
    @memberships = @group.memberships.includes(:person).paginate(page: params[:page], per_page: 100)
    if params[:birthdays]
      @memberships = @memberships.order_by_birthday
    else
      @memberships = @memberships.order_by_name
    end
    @requests = @group.membership_requests
  end

  # join group
  def create
    @person = Person.find(params[:id])
    if @logged_in.can_create?(@group.memberships.new)
      @group.memberships.create(person: @person)
    elsif me?
      @group.membership_requests.create(person: @person)
      flash[:warning] = t('groups.join.request_sent')
    end
    redirect_to :back
  end

  def update
    if params[:email]
      update_email
    elsif params[:promote] && @logged_in.can_update?(@group)
      update_admin
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  def update_email
    @person = Person.find(params[:id])
    if can_update_email?
      @get_email = params[:email] == 'on'
      @group.set_options_for @person, get_email: @get_email
      respond_to do |format|
        format.html do
          flash[:notice] = t('groups.email_settings_changed')
          redirect_to :back
        end
        format.js
      end
    else
      render text: t('not_authorized'), layout: true, status: 401
    end
  end

  def update_admin
    @membership = @group.memberships.find(params[:id])
    @membership.update_attribute(:admin, params[:promote] == 'true')
    flash[:notice] = t('groups.user_settings_saved')
    redirect_to :back
  end

  # leave group
  def destroy
    @membership = @group.memberships.where(person_id: params[:id]).first!
    if @logged_in.can_delete?(@membership)
      if @membership.only_admin?
        flash[:warning] = t('groups.last_admin_remove', name: @membership.person.name)
      else
        @membership.destroy
      end
    end
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def batch
    batch = MembershipBatch.new(@group, params[:ids])
    if request.post?
      batch.delete_requests
      @added = batch.create unless params[:commit] == 'ignore'
    elsif request.delete?
      batch.delete
    end
    @added ||= []
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end

  private

  def can_update_email?
    @logged_in.can_update?(@group) || @logged_in.can_update?(@person)
  end

  def authorize_group_for_read
    return if @logged_in.can_read?(@group)
    render text: t('not_authorized'), layout: true, status: :unauthorized
    false
  end

  def authorize_group_for_update
    return if @logged_in.can_update?(@group)
    render text: t('not_authorized'), layout: true, status: :unauthorized
    false
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_membership.haml
- person = membership.person
%tr.row-with-avatar{ id: "membership_#{membership.id}", style: defined?(hide) ? 'display:none' : '' }
  - if @logged_in.can_update?(@group)
    %td
      = check_box_tag 'ids[]', person.try(:id), false, class: 'checkbox simple'
  %td.avatar
    = avatar_tag person
  %td
    = link_to person.name, person
  - if params[:birthdays]
    %td
      = person.birthday.to_s(:date_without_year) if person.birthday
  - else
    %td
      = membership.created_at.to_s(:date) if membership.created_at
  - if @logged_in.can_update?(@group)
    %td.actions
      - if (@group.linked? or @group.parents_of?) and not membership.auto?
        = icon 'fa fa-exclamation-circle text-gray', title: t('memberships.index.details.manual.tooltip')
      - if membership.admin?
        = link_to group_membership_path(@group, membership, promote: false), data: { method: :put, confirm: t('are_you_sure') }, class: 'btn btn-warning btn-xs', title: t('memberships.demote') do
          = icon 'fa fa-toggle-down'
      - else
        = link_to group_membership_path(@group, membership, promote: true), data: { method: :put, confirm: t('are_you_sure') }, class: 'btn btn-info btn-xs', title: t('memberships.promote') do
          = icon 'fa fa-toggle-up'

app/views/memberships/batch.js.erb
if($('#memberships').length == 0) {
  location.reload();
} else {
  $('#memberships').prepend('<%= escape_javascript render(partial: 'membership', collection: @added, locals: { hide: true }) %>');
  $('<%= @added.map { |m| '#'+dom_id(m) }.join(',') %>').fadeIn(800);
  $('#add_person_name').val('')[0].focus();
  $('#add_people_form input[type="checkbox"]').attr('checked', false);
}

app/views/memberships/destroy.js.erb
$('#person<%= params[:id] %>').hide('slow', function(){$(this).detach()});
$('#people-heading').html('<%= escape_javascript t('people.person', count: @group.people.count) %>');

app/views/memberships/index.html.haml
- @title = t('.heading', group: link_to(@group.name, @group)).html_safe

.row

  .col-md-8
    - if @logged_in.can_update?(@group) and @requests.any?
      = form_tag batch_group_memberships_path(@group) do |form|
        .box.box-warning
          .box-header
            %h3.box-title= t('memberships.requests.heading')
          .box-body
            %table.table.print-full-width
              %tr
                %th{ style: 'width:75px' }
                %th
                %th= t('memberships.requests.name')
                %th= t('memberships.requests.created_at')
              - @requests.each do |req|
                %tr.row-with-avatar
                  %td
                    = check_box_tag 'ids[]', req.person.try(:id), false, class: 'checkbox'
                  %td.avatar
                    = avatar_tag req.person
                  %td
                    = link_to req.person.try(:name), req.person
                  %td
                    = req.created_at.to_s(:date)
          .box-footer
            .form-group
              = t('memberships.requests.select_some')
            .form-group
              = button_tag name: 'commit', value: 'accept', class: 'btn btn-success' do
                = icon 'fa fa-plus-circle'
                = t('memberships.requests.accept.button')
              = button_tag name: 'commit', value: 'ignore', class: 'btn btn-danger' do
                = icon 'fa fa-minus-circle'
                = t('memberships.requests.ignore.button')

    = pagination @memberships

    - if @group.people.any?
      = form_tag batch_group_memberships_path(@group), method: :delete do
        %table.members.table.print-full-width
          %thead
            %tr
              - if @logged_in.can_update?(@group)
                %th{ style: 'width:75px' }
              %th
              %th= t('.details.name')
              - if params[:birthdays]
                %th= t('.details.birthday')
              - else
                %th= t('.details.created_at')
              - if @logged_in.can_update?(@group)
                %th
          %tbody#memberships
            - @memberships.includes(:person).order('people.last_name', 'people.first_name').each do |membership|
              - if person = membership.person
                = render partial: 'membership', object: membership

        - if @logged_in.can_update?(@group)
          .page-controls
            = button_tag class: 'btn btn-delete' do
              = icon 'fa fa-minus-circle'
              = t('.remove.button')

    - else
      %p= t('none')

    = pagination @memberships

  .col-md-4.hidden-print
    - if @logged_in.can_update?(@group)
      .box.box-success
        .box-header
          %h3.box-title
            = t('memberships.add.heading')
        .box-body
          - if @group.approved?
            = form_tag search_path, remote: true do
              = hidden_field_tag :select_person, true
              .form-group
                = label_tag :add_person_name do
                  = t('memberships.add.description')
                = text_field_tag 'name', nil, id: 'add_person_name', class: 'form-control', placeholder: t('memberships.add.name_placeholder')
                - if @group.parents_of?
                  .callout.callout-danger.push-down
                    = t('memberships.add.parents_of_warning_html', group: link_to(@group.parents_of_group.try(:name), @group.parents_of_group))
                - elsif @group.linked?
                  .callout.callout-danger.push-down
                    = t('memberships.add.linked_group_warning_html', code: @group.link_code)
              .form-group
                = button_tag t('search.search_by_name'), class: 'btn btn-info'
            #add_member{ style: 'display:none' }
              = form_tag batch_group_memberships_path(@group), remote: true, id: 'add_people_form' do
                = hidden_field_tag(:birthdays, true) if params[:birthdays]
                #results
                %p= button_tag t('search.add_selected'), class: 'btn btn-success'
          - else
            %p.very-strong
              = t('memberships.group_pending_approval')

app/views/memberships/update.js.erb
toggle = $('#group<%= @group.id %>');

<% if @get_email %>
  toggle.find('a.off').removeClass('toggle-disabled').addClass('toggle-enabled' );
  toggle.find('a.on' ).removeClass('toggle-enabled' ).addClass('toggle-disabled');
<% else %>
  toggle.find('a.on' ).removeClass('toggle-disabled').addClass('toggle-enabled' );
  toggle.find('a.off').removeClass('toggle-enabled' ).addClass('toggle-disabled');
<% end %>