config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get :favs
      get :testimony
      get :login
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :services, :albums, :verses
    resource :privacy
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    resource :photo
    resources :relationships
    resources :people do
      member do
        post :update_position
      end
    end
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resources :tasks do
      member do
        patch :complete
        post :update_position
      end
    end
    resource :stream
    resource :photo
    resources :prayer_requests, :albums
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resource :emails

  put 'setup_email' => 'emails#create_route'

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :shares,
            :comments, :prayer_requests, :generated_files

  resources :verses do
    get 'search', on: :collection
  end

  resource :setup, :session, :search, :printable_directory

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  resources :directory_maps do
    collection do
      get :family_locations
    end
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'
  get '/admin/reports' => 'administration/reports#index'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths, :labels
    end
  end

  resource :checkin, controller: 'checkin/checkins'
  namespace :checkin do
    resource :print
    resource :printer
    resources :families, :people, :groups
  end
  resources :custom_reports

  post '/pusher/auth_printer' => 'pusher#auth_printer'
end

app/models/concerns/person/friend.rb
require 'active_support/concern'

module Concerns
  module Person
    module Friend
      extend ActiveSupport::Concern

      included do
        has_many :friendships
        has_many :friends, -> { order('people.last_name', 'people.first_name') }, class_name: 'Person', through: :friendships
        has_many :friendship_requests
        has_many :pending_friendship_requests, -> { where(rejected: false) }, class_name: 'FriendshipRequest'
        after_destroy :destroy_friendships
      end

      def request_friendship_with(person)
        if pending = self.pending_friendship_requests.where(from_id: person.id).first
          pending.accept
          I18n.t('friends.added_as_friend', name: person.name)
        elsif self.can_request_friendship_with?(person)
          friendship_requests.where(from_id: person.id, rejected: true).delete_all
          person.friendship_requests.create!(from: self)
          I18n.t('friends.request_sent', name: person.name)
        elsif self.friendship_waiting_on?(person)
          I18n.t('friends.already_pending', name: person.name)
        elsif self.friendship_rejected_by?(person)
          I18n.t('friends.cannot_request', name: person.name)
        else
          raise I18n.t('friends.unknown_state')
        end
      end

      def can_request_friendship_with?(person)
        Setting.get(:features, :friends) and
        person != self and
        person.family_id != self.family_id and
        !friend?(person) and
        full_access? and
        person.full_access? and
        person.email.present? and
        person.friends_enabled and
        !friendship_rejected_by?(person) and
        !friendship_waiting_on?(person)
      end

      def friendship_rejected_by?(person)
        person.friendship_requests.where(from_id: id, rejected: true).any?
      end

      def friendship_waiting_on?(person)
        person.friendship_requests.where(from_id: id, rejected: false).any?
      end

      def friend?(person)
        friends.where('friendships.friend_id' => person.id).count > 0
      end

      def destroy_friendships
        friendships.destroy_all
        friendship_requests.destroy_all
      end
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  before_filter :person_must_be_user, except: %w(index)

  def index
    @person = Person.find(params[:person_id])
    if @logged_in.can_read?(@person)
      @pending = me? ? @person.pending_friendship_requests : []
      @friendships = @person.friendships.to_a.select { |f| f.friend and @logged_in.can_read?(f.friend) }
    else
      render text: t('people.not_found'), layout: true, status: 404
    end
  end

  # friend_id = Person (other person)
  def create
    @person = Person.find(params[:person_id])
    @other_person = Person.find(params[:friend_id])
    @message = @person.request_friendship_with(@other_person)
    respond_to do |wants|
      wants.html
      wants.js
    end
  end

  # id = FriendshipRequest
  def update
    @person = Person.find(params[:person_id])
    @friendship_request = @person.friendship_requests.find(params[:id])
    if params[:accept]
      @friendship_request.accept
      flash[:notice] = t('people.friendship_accepted')
      redirect_to person_friends_path(@person)
    elsif params[:reject]
      @friendship_request.reject
      flash[:notice] = t('people.friendship_rejected')
      redirect_to person_friends_path(@person)
    else
      render text: t('people.friendship_must_specify'), layout: true, status: 500
    end
  end

  # id = Person (friend)
  def destroy
    @person = Person.find(params[:person_id])
    if @friendship = @person.friendships.where(friend_id: params[:id]).first
      @friendship.destroy
      redirect_to person_friends_path(@person)
    else
      render text: t('people.friend_not_found'), layout: true, status: 404
    end
  end

  def reorder
    @person = Person.find(params[:person_id])
    params[:friends].each_with_index do |id, index|
      if f = @person.friendships.where(id: id).first
        f.update_attribute :ordering, index
      end
    end
    render nothing: true
  end

  private

    def person_must_be_user
      unless @logged_in.id == params[:person_id].to_i
        render text: t('people.friendship_manage'), layout: true, status: 401
        return false
      end
    end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/create.html.erb
<%= @message %>

app/views/friends/create.js.erb
button = $('#add_friend_<%= @other_person.id %>');
button.find('.text').text(button.data('pending-label'))
button.addClass('disabled');
alert('<%= escape_javascript @message %>');

app/views/friends/index.html.haml
- @title = t('friends.personal_friends', name: @person.name)

- if @pending.any?
  .box.box-solid.box-success
    .box-header
      %h3.box-title
        = icon 'fa fa-clock-o'
        = t('friends.pending_requests')
    .box-body
      %p= t('friends.people_requested')
      %ul.list-group{style: 'max-width: 500px'}
        - @pending.each do |friendship_request|
          %li.list-group-item
            = link_to friendship_request.from do
              = avatar_tag(friendship_request.from)
              = friendship_request.from.name
            .pull-right
              = link_to person_friend_path(@logged_in, friendship_request, accept: true), method: 'put', class: 'btn btn-success' do
                = icon 'fa fa-plus-circle'
                = t('friends.accept')
              = link_to person_friend_path(@logged_in, friendship_request, reject: true), method: 'put', data: { confirm: t('are_you_sure') }, class: 'btn bg-gray text-red' do
                = icon 'fa fa-minus-circle'
                = t('friends.decline')

%h3= t('friends.friends')
- if @friendships.any?
  %ul#friends.list-group{style: 'max-width: 600px'}
    - @friendships.each do |friendship|
      %li.list-group-item{:id => "friendship_#{friendship.id}"}
        = link_to friendship.friend do
          = avatar_tag friendship.friend
        = link_to friendship.friend.name, friendship.friend
        (added #{friendship.created_at.to_time.to_s})
        - if me?
          = link_to person_friend_path(@person, friendship.friend), class: 'btn bg-gray text-red pull-right', method: 'delete', data: { confirm: t('are_you_sure') } do
            = icon 'fa fa-minus-circle'
            = t('friends.remove_from_friends')
          .clearfix
  = javascript_include_tag 'dragdrop.js'
- else
  %p= t('.nobody_yet')
- if me?
  %p.double-margin-top
    = link_to search_path, class: 'btn btn-info' do
      = icon 'fa fa-search'
      = t('friends.search_in_the_directory')