config/routes.rb
OneBody::Application.routes.draw do

  root to: redirect('/stream')

  resource :account do
    member do
      get :verify_code
      post :verify_code
      get  :select
      post :select
    end
  end

  resources :people do
    collection do
      get  :schema
      get  :import
      post :import
      post :hashify
      post :batch
      put  :import
    end
    member do
      get :favs
      get :testimony
      get :login
    end
    resources :friends do
      collection do
        post :reorder
      end
    end
    resources :relationships do
      collection do
        post :batch
      end
    end
    resource :account do
      member do
        get  :verify_code
        post :verify_code
        get  :select
        post :select
      end
    end
    resource :stream
    resource :photo
    resources :groups, :pictures, :services, :albums, :verses
    resource :privacy
  end

  resources :families do
    collection do
      get  :schema
      post :hashify
      post :batch
      post :select
    end
    resource :photo
    resources :relationships
    resources :people do
      member do
        post :update_position
      end
    end
    resource :search
  end

  resources :groups do
    collection do
      get  :batch
      post :batch
    end
    resources :memberships do
      collection do
        post   :batch
        delete :batch
      end
      resource :privacy
    end
    resources :messages do
      collection do
        post :new # XXX why??
      end
    end
    resources :attendance do
      collection do
        post :batch
      end
    end
    resources :tasks do
      member do
        patch :complete
        post :update_position
      end
    end
    resource :stream
    resource :photo
    resources :prayer_requests, :albums
    resource :calendar
  end

  resources :memberships do
    collection do
      get  :batch
      post :batch
    end
  end

  resources :service_categories do
    collection do
      get :batch_edit
      get :close_batch_edit
    end
  end

  resources :albums do
    resources :pictures do
      member do
        get :next
        get :prev
      end
      resource :photo
    end
  end

  resources :messages do
    resources :attachments
  end

  resource :emails

  put 'setup_email' => 'emails#create_route'

  resources :tags, only: :show

  resources :pictures, :prayer_signups, :authentications, :shares,
            :comments, :prayer_requests, :generated_files

  resources :verses do
    get 'search', on: :collection
  end

  resource :setup, :session, :search, :printable_directory

  resource :stream do
    resources :people, controller: 'stream_people'
  end

  resources :news, as: :news_items
  get 'news', to: 'news#index'

  resources :attachments do
    member do
      get :get
    end
  end

  resources :pages, path: 'pages/admin' do
    resources :attachments
  end

  resources :documents do
    get :download, on: :member
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  resources :directory_maps do
    collection do
      get :family_locations
    end
  end

  get 'pages/*path' => 'pages#show_for_public', via: :get, as: :page_for_public

  get '/admin' => 'administration/dashboards#show'
  get '/admin/reports' => 'administration/reports#index'

  namespace :administration, path: :admin do
    resources :emails do
      collection do
        put :batch
      end
    end
    resources :settings do
      collection do
        put :batch
        put :reload
      end
    end
    resources :attendance do
      collection do
        get :prev
        get :next
      end
    end
    resources :syncs do
      member do
        post :create_items
      end
    end
    resources :deleted_people do
      collection do
        put :batch
      end
    end
    resources :updates, :admins, :membership_requests
    namespace :checkin do
      root to: 'dashboards#show'
      resource :dashboard
      resources :groups do
        put :batch, on: :collection
        put :reorder, on: :member
      end
      resources :times do
        resources :groups
      end
      resources :cards, :auths, :labels
    end
  end

  resource :checkin, controller: 'checkin/checkins'
  namespace :checkin do
    resource :print
    resource :printer
    resources :families, :people, :groups
  end
  resources :custom_reports

  post '/pusher/auth_printer' => 'pusher#auth_printer'
end

app/models/concerns/person/relationships.rb
require 'active_support/concern'

module Concerns
  module Person
    module Relationships
      extend ActiveSupport::Concern

      included do
        has_many :relationships, dependent: :delete_all
        has_many :related_people, class_name: 'Person', through: :relationships, source: :related
        has_many :inward_relationships, class_name: 'Relationship', foreign_key: 'related_id', dependent: :delete_all
        has_many :inward_related_people, class_name: 'Person', through: :inward_relationships, source: :person
      end

      def update_relationships_hash
        rels = relationships.includes(:related).to_a.select do |relationship|
          !Setting.get(:system, :online_only_relationships).include?(relationship.name_or_other)
        end.map do |relationship|
          "#{relationship.related.legacy_id}[#{relationship.name_or_other}]"
        end.sort
        self.relationships_hash = Digest::SHA1.hexdigest(rels.join(','))
      end

      def update_relationships_hash!
        update_relationships_hash
        save(validate: false)
      end
    end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :person
  belongs_to :related, foreign_key: 'related_id', class_name: 'Person'

  scope_by_site_id

  validates_presence_of :name
  validates_presence_of :other_name, if: Proc.new { |r| r.name == 'other' }
  validates_presence_of :person_id
  validates_presence_of :related_id
  validates_uniqueness_of :name, scope: [:site_id, :other_name, :person_id, :related_id]
  validates_uniqueness_of :other_name, scope: [:site_id, :name, :person_id, :related_id]
  validates_each :name do |record, attribute, value|
    unless I18n.t('relationships.names').keys.map(&:to_s).include?(value) or value == 'other'
      record.errors.add attribute, :inclusion
    end
  end

  def name_or_other
    name == 'other' ? other_name : I18n.t(name, scope: 'relationships.names')
  end

  def reciprocate
    if can_auto_reciprocate?
      Relationship.create(person: related, related: person, name: reciprocal_name)
    end
  end

  def reciprocal_name
    RECIPROCAL_RELATIONSHIP_NAMES[name][person.gender]
  end

  def can_auto_reciprocate?
    !reciprocal_name.nil?
  end

  def self.other_names
    connection.select_values("select distinct other_name from relationships where other_name is not null and other_name != '' and site_id=#{Site.current.id} order by other_name")
  end

  after_save :update_relationships_hash
  after_destroy :update_relationships_hash
  def update_relationships_hash
    person.update_relationships_hash!
  end

  RECIPROCAL_RELATIONSHIP_NAMES = {
    'aunt'            => {'Male' => 'nephew',         'Female' => 'niece'          },
    'brother'         => {'Male' => 'brother',        'Female' => 'sister'         },
    'brother_in_law'  => {'Male' => 'brother_in_law', 'Female' => 'sister_in_law'  },
    'cousin'          => {'Male' => 'cousin',         'Female' => 'cousin'         },
    'daughter'        => {'Male' => 'father',         'Female' => 'mother'         },
    'daughter_in_law' => {'Male' => 'father_in_law',  'Female' => 'mother_in_law'  },
    'father'          => {'Male' => 'son',            'Female' => 'daughter'       },
    'father_in_law'   => {'Male' => 'son_in_law',     'Female' => 'daughter_in_law'},
    'granddaughter'   => {'Male' => 'grandfather',    'Female' => 'grandmother'    },
    'grandfather'     => {'Male' => 'grandson',       'Female' => 'granddaughter'  },
    'grandmother'     => {'Male' => 'grandson',       'Female' => 'granddaughter'  },
    'grandson'        => {'Male' => 'grandfather',    'Female' => 'grandmother'    },
    'husband'         => {                            'Female' => 'wife'           },
    'mother'          => {'Male' => 'son',            'Female' => 'daughter'       },
    'mother_in_law'   => {'Male' => 'son_in_law',     'Female' => 'daughter_in_law'},
    'nephew'          => {'Male' => 'uncle',          'Female' => 'aunt'           },
    'niece'           => {'Male' => 'uncle',          'Female' => 'aunt'           },
    'other'           => {                                                         },
    'sister'          => {'Male' => 'brother',        'Female' => 'sister'         },
    'sister_in_law'   => {'Male' => 'brother_in_law', 'Female' => 'sister_in_law'  },
    'son'             => {'Male' => 'father',         'Female' => 'mother'         },
    'son_in_law'      => {'Male' => 'father_in_law',  'Female' => 'mother_in_law'  },
    'stepbrother'     => {'Male' => 'stepbrother',    'Female' => 'stepsister'     },
    'stepdaughter'    => {'Male' => 'stepfather',     'Female' => 'stepmother'     },
    'stepfather'      => {'Male' => 'stepson',        'Female' => 'stepdaughter'   },
    'stepmother'      => {'Male' => 'stepson',        'Female' => 'stepdaughter'   },
    'stepsister'      => {'Male' => 'stepbrother',    'Female' => 'stepsister'     },
    'stepson'         => {'Male' => 'stepfather',     'Female' => 'stepmother'     },
    'uncle'           => {'Male' => 'nephew',         'Female' => 'niece'          },
    'wife'            => {'Male' => 'husband'                                      }
  }
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :only_admins

  def index
    if params[:person_id]
      person_index
    elsif params[:family_id]
      family_index
    else
      render text: t('relationships.no_person_selected'), layout: true
    end
  end

  def person_index
    @person = Person.undeleted.find(params[:person_id])
    @relationships = @person.relationships.includes(:related).order('people.last_name', 'people.first_name')
    @inward_relationships = @person.inward_relationships.includes(:person).order('people.last_name', 'people.first_name')
    @other_names = Relationship.other_names
    @relationship = Relationship.new(person: @person)
    respond_to do |format|
      format.html { render action: 'person_index' }
      format.xml  { render xml: @relationships }
    end
  end

  def family_index
    @family = Family.undeleted.find(params[:family_id])
    people_ids = @family.people.map { |p| p.id }
    @relationships = Relationship.where("person_id in (?) and related_id in (?)", people_ids, people_ids)
    @unique_relationships = {}
    @relationships.each do |relationship|
      @unique_relationships[relationship.related] ||= []
      @unique_relationships[relationship.related] << relationship.name_or_other
      @unique_relationships[relationship.related].uniq!
    end
    @suggested_relationships = @family.suggested_relationships
    render action: 'family_index'
  end

  def create
    if params[:person_id]
      create_for_person
    elsif params[:family_id]
      create_for_family
    else
      render text: t('relationships.no_person_selected'), layout: true
    end
  end

  def create_for_person
    @person = Person.undeleted.find(params[:person_id])
    @related = Person.undeleted.find(Array(params[:ids]).first)
    @relationship = Relationship.new(person: @person, related: @related, name: params[:name], other_name: params[:other_name])
    respond_to do |format|
      if @relationship.save
        format.html { redirect_to person_relationships_path(@person) }
        format.xml  { render xml: @relationship, status: :created, location: person_relationship_path(@person, @relationship) }
      else
        format.html { add_errors_to_flash(@relationship); redirect_to person_relationships_path(@person) }
        format.xml  { render xml: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_for_family
    @family = Family.undeleted.find(params[:family_id])
    params[:people].to_a.each do |person_id, relationships|
      relationships.each do |related_id, relationship|
        Relationship.create(
          person:  @family.people.find(person_id),
          related: @family.people.find(related_id),
          name:    relationship
        )
      end
    end
    redirect_to family_relationships_path(@family)
  end

  def destroy
    @person = Person.undeleted.find(params[:person_id])
    @person.relationship.find(params[:id]).destroy
    respond_to do |format|
      format.xml { head :ok }
    end
  end

  def batch
    @person = Person.undeleted.find(params[:person_id])
    params[:ids].to_a.each do |id|
      if relationship = Relationship.where("id = ? and (person_id = ? or related_id = ?)", id, @person.id, @person.id).first
        if params[:delete]
          relationship.destroy
        elsif params[:reciprocate]
          r = relationship.reciprocate
          if r.nil?
            flash[:warning] ||= ''
            flash[:warning] << t('relationships.reciprocate.failure', name: relationship.related.name) + "\n"
          elsif !r.valid?
            add_errors_to_flash(r)
          end
        end
      end
    end
    redirect_to person_relationships_path(@person)
  end

  private

    def only_admins
      unless @logged_in.admin?(:edit_profiles)
        render text: t('only_admins'), layout: true, status: 401
        return false
      end
    end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper

  def relationships_for_select
    options_for_select(relationship_labels)
  end

  def relationship_labels
    I18n.t('relationships.names').dup.tap do |hash|
      hash[:other] = hash.delete(:other_name) # OneSky doesn't like the key 'other'
    end.invert.sort
  end

end

app/views/relationships/family_index.html.haml
- @title = t('relationships.family.heading', family: link_to(@family.name, @family)).html_safe

- if @relationships.any?
  %table#unique_relationships.table
    %tr
      %th= t('name')
      %th= t('relationships.relationship')
      %th
    - @unique_relationships.each do |person, relationship_names|
      %tr
        %td= link_to person.name, person_relationships_path(person)
        %td= relationship_names.join(', ')
  %table#individual_relationships.table{ style: "display:none" }
    %tr
      %th= t('From')
      %th= t('relationships.relationship')
      %th
    - @relationships.each do |relationship|
      %tr
        %td= link_to relationship.person.name, person_relationships_path(relationship.person)
        %td= link_to relationship.related.name, person_relationships_path(relationship.related)
        %td= relationship.name_or_other

- if @relationships.any? or @family.people.any?
  .page-controls
    - if @relationships.any?
      = link_to_function t('relationships.toggle_individual'), "$('#unique_relationships, #individual_relationships').toggle();", class: 'btn bg-gray'
    - if @family.people.any?
      = link_to_function t('relationships.family.create.button'), "$('#auto_generate').show()", class: 'btn bg-gray'

- else
  %p
    %em= t('none')
- if @family.people.count > 0
  #auto_generate{:style => "display:none;"}
    = form_tag family_relationships_path(@family) do
      %p= t('relationships.family.create.intro')
      %table.table
        %tr
          %th= t('From')
          %th= t('To')
          %th= t('relationships.relationship')
          %th
        - @suggested_relationships.each do |person, relationships|
          - relationships.each do |related, relationship|
            %tr
              %td= link_to person.name, person
              %td= link_to related.name, related
              %td= select_tag "people[#{person.id}][#{related.id}]", options_for_select([["(#{t('none')})", '']]+relationship_labels, relationship.to_sym)
      = button_tag t('relationships.family.create.button'), class: 'btn btn-success'

app/views/relationships/person_index.html.haml
- @title = t('relationships.heading', person: link_to(@person.name, @person)).html_safe

.row
  .col-md-8
    - if @relationships.any?
      = form_tag batch_person_relationships_path(@person) do
        %table.table
          %tr
            %th
              %input{ onclick: "$('.outward_relationship_checkbox').attr('checked', this.checked)", type: "checkbox" }
            %th= t('name')
            %th
              = t('relationships.relationship')
            %th
              - @relationships.each do |relationship|
                %tr
                  %td= check_box_tag 'ids[]', relationship.id, false, class: 'outward_relationship_checkbox'
                  %td= link_to relationship.related.name, person_relationships_path(relationship.related)
                  %td= relationship.name_or_other
        .form-group.push-down
          = button_tag name: 'delete', data: { confirm: t('are_you_sure') }, class: 'btn btn-delete' do
            = icon 'fa fa-trash-o'
            = t('Delete')
          = button_tag name: 'reciprocate', class: 'btn btn-success' do
            = icon 'fa fa-exchange'
            = t('relationships.reciprocate.button')
    - else
      %p
        %em= t('none')

    = form_tag search_path, remote: true do
      = hidden_field_tag :select_person, true
      %p= t('relationships.add_relationship.intro')
      .form-group
        %label{ for: "name" }= t('search.search_by_name')
        = text_field_tag 'name', '', class: 'form-control'
      .form-group
        = button_tag t('relationships.add_relationship.button'), class: 'btn btn-info'
    #add_member{ style: "display:none;" }
      = form_tag person_relationships_path(@person) do
        .form-group
          %label{for: 'relationship_name'}= t('relationships.relationship_type')
          = select_tag :name, relationships_for_select, |
            id: 'relationship_name', |
            class: 'form-control', |
            include_blank: true, |
            data: { toggle: '#other_name', 'toggle-value' => 'other' }
        = text_field_tag :other_name, nil, |
          style: 'display:none;', |
          class: 'form-control', |
          placeholder: t('relationships.other_name.placeholder')
        #results
        .form-group
          = button_tag t('search.add_selected'), class: 'btn btn-success'

  .col-md-4
    .page-controls
      = link_to family_relationships_path(@person.family), class: 'btn btn-info' do
        = icon 'fa fa-group'
        = t('relationships.family.button')

    .box.box-info
      .box-header
        %h3.box-title= t('relationships.inward.heading')
      .box-body
        - if @inward_relationships.any?
          = form_tag batch_person_relationships_path(@person) do
            %table.table
              %tr
                %th
                  %input{ onclick: "$('.inward_relationship_checkbox').attr('checked', this.checked)", type: "checkbox" }
                %th= t('From')
                %th= t('relationships.relationship')
              - @inward_relationships.each do |relationship|
                %tr
                  %td= check_box_tag 'ids[]', relationship.id, false, class: 'inward_relationship_checkbox'
                  %td= link_to relationship.person.name, person_relationships_path(relationship.person)
                  %td= relationship.name_or_other
            .form-group.push-down
              = button_tag name: 'delete', data: { confirm: t('are_you_sure') }, class: 'btn btn-delete' do
                = icon 'fa fa-trash-o'
                = t('Delete')
              = button_tag name: 'reciprocate', class: 'btn btn-success' do
                = icon 'fa fa-exchange'
                = t('relationships.reciprocate.button')
        - else
          %p
            %em= t('none')